FACG5/PBI

- package-lock.json
- package.json
- src/app.js
- src/database/dbConnect.js
- src/database/models/admin.js
- src/database/models/certificate.js
- src/database/models/employee.js
- src/database/models/fixedVarible.js
- src/database/models/purchaseBox.js
- src/database/models/purchasesEmployee.js
- src/database/models/report.js
- src/index.js
relates to #2
creating the database schema and necessary files for connecting to the database
> database schema

- src/middleware/convertCamelToSnake.js
> convert camel-case to snake-case 

- src/views/partials/sidebar.hbs
> Edit the routes in the sidebar

- public/css/cart.css
- public/css/swal.css
- public/js/cart.js
- src/controllers/cart.js
- src/controllers/index.js
- src/views/cart.hbs
Relates #11 
- Delete the cart from database
> delete the cart

- public/js/generalSetting.js
- src/controllers/generalSettings.js
- src/views/generalSettings.hbs
> fixing error in editing general Setting #51

- src/controllers/index.js
relates to #30 
error page routes in controller
missed lines
```
const errors = require('./errors');
router.use(errors.client);
router.use(errors.server);
```
> fixing error page router #30

- src/views/employeeDetails.hbs
> employee page

- public/js/employees.js
- src/controllers/employees.js
- src/views/employees.hbs
related to #8
create a filter to the employee table
> Filter  employee table

- src/controllers/login.js
> edit the maxAge to 30 minutes

- public/css/tables.css
- src/controllers/employees.js
- src/views/employees.hbs
> Add link to employees

- src/controllers/login.js
- src/views/layouts/main.hbs
- remove the link of validator.js in front-end
> editions of the code

- src/controllers/generalSettings.js
- making some edits in generalSettings handilng error and validator
> edits in generalSetting

- public/js/employeeDetails.js
- src/controllers/addEmployee.js
- src/controllers/editEmployee.js
- src/controllers/employeeDetails.js
- src/controllers/helpers/deductionsOperations.js
- src/controllers/helpers/salaryMain.js
- src/database/query/bonusQueryOneEmployee.js
- src/database/query/deductionsQuery.js
- src/database/query/exemptions.js
- src/views/addEmployee.hbs
- src/views/employeeDetails.hbs
- src/views/layouts/main.hbs
relates to #45 
in this pull request , we solve a problems in edit employee
> Fix edit employee

- src/controllers/helpers/excelSheets/columns.js
- src/controllers/helpers/excelSheets/dataSet.js
- src/controllers/helpers/excelSheets/excelSheetMain.js
- src/controllers/helpers/salaryMain.js
- src/controllers/reports.js
this relates to #96 
- edit width of some columns
- use try/catch with download report method in controller
- create new function to convert the values to be in two decimal number before store it in report table
- use async/await instead of 'Promis' in mainMethod file of excel and dataSet Method
> Excel enhancement

- .eslintrc.json
- public/js/addEmployee.js
- public/js/logout.js
> General editions

- config.js
- package.json
- src/database/config/connection.js
- create config file which contain values in development and production phase
- add NODE_ENV=development in dev script in package.json
- get values from config file in connection file
> deploy on heroku

- public/js/addEmployee.js
- src/controllers/addEmployee.js
- src/controllers/employeeDetails.js
- src/controllers/files.js
- src/controllers/index.js
- src/views/employeeDetails.hbs
in this pull request which is relates to #9 
admin can see the certificate of employee with it's link and he can download it ,
changes are in 
- controller so we add the route of download files /download by using get method
- add get method to files.js so get the file from server and return it to the response and download it
> Download certficate

- public/js/employeeDetails.js
- src/views/employeeDetails.hbs
related to #99
when edmin edit employee, after save the page will return to the same section which edit 
* employeeDetails.js in public 
* employeeDetails.hbs in src
> edit employee

- public/css/employeeDetails.css
- public/js/employeeDetails.js
- src/controllers/editEmployee.js
- src/controllers/employeeDetails.js
- src/database/query/purchaseEmployees.js
- src/database/query/updatePurchase.js
- src/views/employeeDetails.hbs
admin can edit purchase box for each employee so can add value in any existing purchase box 
- add new query to get all of purchase box in site 
- and new query to update purchase_employee table which contain the relation between employee and every purchase box
- edit editEmployee hbs file , to be consistent with updating purchase box value 
- edit css file of editEmployee
> Update purchase boxex for each employee 

- public/css/employees.css
- public/js/addEmployee.js
- public/js/employeeDetails.js
> Loading div

- src/controllers/employeeReport.js
- src/views/addEmployee.hbs
- src/views/employeeReport.hbs
> fixing error in hbs files
